server:
  port: ${PORT:5001}
spring:
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:8080}/${DATABASE_NAME:dflmngrdb}
    username: ${JDBC_DATABASE_USERNAME:dflmngr}
    password: ${JDBC_DATABASE_PASSWORD:dflmngr}
    hikari:
      connection-timeout: 5000
      minimum-idle: 2
      maximum-pool-size: 5

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    enabled: false  # Migrations run via pre-deploy hook only

logging:
  level:
    net:
      dflmngr: ${DFLMNGR_LOG_LEVEL:info}
