package net.dflmngr.repositories;

import org.junit.jupiter.api.BeforeEach;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

/**
 * Base class for repository integration tests.
 *
 * Uses H2 in-memory database locally, PostgreSQL in CI (GitHub Actions).
 * Schema is auto-generated by Hibernate from JPA entities.
 * Transactions roll back after each test for clean state.
 */
@SpringBootTest(classes = TestConfiguration.class)
@Transactional
@ActiveProfiles("test")
public abstract class AbstractRepositoryIntegrationTest {

    /**
     * Override this method in subclasses to set up test data.
     * Called before each test method.
     */
    @BeforeEach
    public void setUp() {
        // Subclasses can override to add test data
    }
}
